"""
Alembic environment config for Aegis.

Reads DATABASE_URL from the environment rather than alembic.ini, so no
credentials ever live in a git-tracked file -- consistent with
db/session.py.

NOTE: this file was hand-written, not generated by `alembic init`,
since alembic isn't installed anywhere I could run it. If
`alembic upgrade head` fails on environment setup (as opposed to
failing inside the migration itself), the more reliable fix is:
run `alembic init alembic` yourself locally to get boilerplate
guaranteed to match your installed version, then copy the DATABASE_URL
wiring below and target_metadata line into the generated file.
"""

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import engine_from_config, pool
from alembic import context

# Make `src` importable the same way the app itself expects.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.db.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

configured_url = config.get_main_option("sqlalchemy.url")
database_url = configured_url or os.environ.get("DATABASE_URL")

if not database_url:
    raise RuntimeError(
        "DATABASE_URL is not set and no sqlalchemy.url was configured "
        "programmatically. Alembic will not guess at database "
        "credentials -- export DATABASE_URL or source your .env first."
    )

# Only overwrite when we fell back to the environment variable --
# don't clobber a URL a caller (e.g. a test) already set explicitly
# via config.set_main_option() before invoking alembic.command.
if not configured_url:
    config.set_main_option("sqlalchemy.url", database_url)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
